# Site settings
title: Rafael R. Nunes
tagline: Desenvolvimento e tecnologias
email: programmer.rrn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor com mais de 3 anos de experiência profissional. 
  Interessado em todos os tipos de desenvolvimento, desktop, web e mobile.
  Criei este canal para compartilhar minha experiência.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
#url: http://localhost:4000
url: "http://rafaelrnunes.github.io" # the base hostname & protocol for your site
#logourl: /assets/images/logo.png # Site logo
author: "RRN"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#2c3e50" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: RafaelRNunes
    #twitter: gayanvirajith
    facebook: RRNProgrammer
    #gplus: +gayanvirajith
    # dribble: gayanvirajith
    #pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: rafaelnunes

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
